// <auto-generated />
using System;
using AirportTool.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportTool.Infrastructure.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirportTool.Infrastructure.Auth.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "97e6ec70-8b4b-4be6-b1be-4d1c88b207d9",
                            Email = "alin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Demo",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALIN@GMAIL.COM",
                            NormalizedUserName = "ALIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED9wWWuVvxJ4th3X6VcywrfAhYEsG56u0ReDw+G4ZX3yXKiG2LEkD/KphecR38vUhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bd9435b5-451c-430e-9a2c-bcca23cd4d59",
                            TwoFactorEnabled = false,
                            UserName = "alin"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eaa4f714-ab54-441b-aced-da3fdcc4ac5a",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Demo",
                            LastName = "Staff",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO5s2vPYKlwziNtcGmai1kdW8iMhqRLUa6ZHxChDKtJEXmgRbs29NWCbFPC1ZS6sbQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "188ebf6d-2344-4668-ad68-a233bbb87da4",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AddressDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AircraftDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TailNumber" }, "UQ_Aircraft_TailNumber")
                        .IsUnique();

                    b.ToTable("Aircraft", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AirlineDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IATACode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IATACode" }, "IX_Airline_IATACode")
                        .IsUnique();

                    b.HasIndex(new[] { "IATACode" }, "UQ_Airline_IATACode")
                        .IsUnique();

                    b.ToTable("Airline", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AirportDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("IATACode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex(new[] { "IATACode" }, "IX_Airport_IATACode")
                        .IsUnique();

                    b.HasIndex(new[] { "IATACode" }, "UQ_Airport_IATACode")
                        .IsUnique();

                    b.ToTable("Airport", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.BookingDAO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BookingStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ConfirmationCode" }, "IX_Booking_ConfirmationCode")
                        .IsUnique();

                    b.HasIndex(new[] { "ConfirmationCode" }, "UQ_Booking_ConfirmationCode")
                        .IsUnique();

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.BookingStatusDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BookingStatus", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.FlightDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultAircraftId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultAircraftId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex(new[] { "AirlineId", "FlightNumber" }, "IX_Flight_Airline_FlightNumber");

                    b.HasIndex(new[] { "OriginAirportId", "DestinationAirportId" }, "IX_Flight_Origin_Destination");

                    b.ToTable("Flight", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.FlightScheduleDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedAircraftId")
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("FlightStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledArrivalUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ScheduledDepartureUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAircraftId");

                    b.HasIndex("FlightStatusId");

                    b.HasIndex("GateId");

                    b.HasIndex(new[] { "FlightId", "ScheduledDepartureUtc" }, "IX_FlightSchedule_Flight_Departure");

                    b.ToTable("FlightSchedule", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.FlightStatusDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FlightStatus", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.GateDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AirportId", "Code" }, "IX_Gate_Airport_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "AirportId", "Code" }, "UQ_Gate_Airport_Code")
                        .IsUnique();

                    b.ToTable("Gate", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.TicketDAO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("FareClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("FlightScheduleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRefundable")
                        .HasColumnType("bit");

                    b.Property<string>("PassengerEmail")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PassengerFullName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SeatInventory")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex(new[] { "FlightScheduleId", "FareClass" }, "IX_Ticket_FlightSchedule_FareClass");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.UserDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UQ_User_Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            ConcurrencyStamp = "USER-CS",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            ConcurrencyStamp = "STAFF-CS",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "33333333-3333-3333-3333-333333333333",
                            RoleId = "11111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            UserId = "44444444-4444-4444-4444-444444444444",
                            RoleId = "22222222-2222-2222-2222-222222222222"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AirportDAO", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Data.Models.AddressDAO", "Address")
                        .WithMany("Airports")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK_Airport_Address");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.BookingDAO", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Data.Models.BookingStatusDAO", "BookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Status");

                    b.HasOne("AirportTool.Infrastructure.Data.Models.UserDAO", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_User");

                    b.Navigation("BookingStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.FlightDAO", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Data.Models.AirlineDAO", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .IsRequired()
                        .HasConstraintName("FK_Flight_Airline");

                    b.HasOne("AirportTool.Infrastructure.Data.Models.AircraftDAO", "DefaultAircraft")
                        .WithMany("Flights")
                        .HasForeignKey("DefaultAircraftId")
                        .HasConstraintName("FK_Flight_DefaultAircraft");

                    b.HasOne("AirportTool.Infrastructure.Data.Models.AirportDAO", "DestinationAirport")
                        .WithMany("FlightDestinationAirports")
                        .HasForeignKey("DestinationAirportId")
                        .IsRequired()
                        .HasConstraintName("FK_Flight_DestinationAirport");

                    b.HasOne("AirportTool.Infrastructure.Data.Models.AirportDAO", "OriginAirport")
                        .WithMany("FlightOriginAirports")
                        .HasForeignKey("OriginAirportId")
                        .IsRequired()
                        .HasConstraintName("FK_Flight_OriginAirport");

                    b.Navigation("Airline");

                    b.Navigation("DefaultAircraft");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.FlightScheduleDAO", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Data.Models.AircraftDAO", "AssignedAircraft")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("AssignedAircraftId")
                        .HasConstraintName("FK_FlightSchedule_AssignedAircraft");

                    b.HasOne("AirportTool.Infrastructure.Data.Models.FlightDAO", "Flight")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("FlightId")
                        .IsRequired()
                        .HasConstraintName("FK_FlightSchedule_Flight");

                    b.HasOne("AirportTool.Infrastructure.Data.Models.FlightStatusDAO", "FlightStatus")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("FlightStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_FlightSchedule_FlightStatus");

                    b.HasOne("AirportTool.Infrastructure.Data.Models.GateDAO", "Gate")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("GateId")
                        .HasConstraintName("FK_FlightSchedule_Gate");

                    b.Navigation("AssignedAircraft");

                    b.Navigation("Flight");

                    b.Navigation("FlightStatus");

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.GateDAO", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Data.Models.AirportDAO", "Airport")
                        .WithMany("Gates")
                        .HasForeignKey("AirportId")
                        .IsRequired()
                        .HasConstraintName("FK_Gate_Airport");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.TicketDAO", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Data.Models.BookingDAO", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_Ticket_Booking");

                    b.HasOne("AirportTool.Infrastructure.Data.Models.FlightScheduleDAO", "FlightSchedule")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_FlightSchedule");

                    b.Navigation("Booking");

                    b.Navigation("FlightSchedule");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Auth.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Auth.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportTool.Infrastructure.Auth.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AirportTool.Infrastructure.Auth.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AddressDAO", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AircraftDAO", b =>
                {
                    b.Navigation("FlightSchedules");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AirlineDAO", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.AirportDAO", b =>
                {
                    b.Navigation("FlightDestinationAirports");

                    b.Navigation("FlightOriginAirports");

                    b.Navigation("Gates");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.BookingDAO", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.BookingStatusDAO", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.FlightDAO", b =>
                {
                    b.Navigation("FlightSchedules");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.FlightScheduleDAO", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.FlightStatusDAO", b =>
                {
                    b.Navigation("FlightSchedules");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.GateDAO", b =>
                {
                    b.Navigation("FlightSchedules");
                });

            modelBuilder.Entity("AirportTool.Infrastructure.Data.Models.UserDAO", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
